### ISSUE TITLE
pip installation has a dependency issue

### ISSUE THREAD

**Issue by webeule** [jdegenstein/jmwright-CQ-Editor#23]
When installing by using pip I get the following error when I try to install cadquery:

Installing collected packages: typish, cadquery-ocp, pyparsing, numpy, multimethod, fonttools, nptyping, nlopt, ezdxf, casadi, cadquery
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cq-editor 0.3.0.dev0 requires numpy<2,>=1.24.1, but you have numpy 2.1.3 which is incompatible.

**Comment by jdegenstein** [comment]
Thanks for reporting, it should be fixed as of the latest commit.
